version: "3.9"

networks:
  laravel_workspace_api:

services: 
  server:
    container_name: laravel_workspace_api_one
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - '8085:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - php
      - mysql
    networks:
      - laravel_workspace_api
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./src:/var/www/html:delegated
    networks:
      - laravel_workspace_api
  mysql:
    image: mysql:8.0.1
    env_file: 
      - ./env/mysql.env
    networks:
      - laravel_workspace_api  
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      - ./src:/var/www/html
    depends_on:
      - php  
    networks:
      - laravel_workspace_api  
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
    depends_on:
      - mysql
    networks:
      - laravel_workspace_api 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin2
    depends_on:
      - mysql
    ports:
      - '8086:80'
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    networks:
      - laravel_workspace_api

